name: build

on: [push]

jobs:
  python:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Show ref
        run: |
          echo "$GITHUB_REF"
      - name: Run the tests
        run: make build db test
      - name: Build a distribution
        run: |
          python setup.py sdist bdist_wheel
      - name: Publish a Python distribution to PyPI
        if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.pypi_password }}
